### ISSUE TITLE
Real world testing

### ISSUE THREAD

**Issue by vibgy** [chirag200666/node-gcm-iid#1]
I am having trouble making this work between my webapp and android app. How are you testing it in the real world? I get message_id back happily, but GCM diagnostics do not recognize that message.

**Comment by chirag200666** [comment]
If you receive message_id back it means the message has been sent to the GCM and google will take care of delivering it, (and that is pretty much all what is required from your server) are you sending the message to a token or a topic ? If you are sending to a topic then the installed app's token has to be registered for that topic, I had implemented that logic in the app. It can also be implemented using the server after you note down the app token, you can use this module's function instanceId.addToTopicNoRetry and pass the token and the topic.

To try out GCM on android I had used the sample app mentioned here : https://developers.google.com/cloud-messaging/android/start .

I have not used GCM statistics yet as on its website it says that it will be available for only published Google Play apps and mine not yet published.

**Comment by vibgy** [comment]
The problem that I'm having is this: 
- From my webapp I pass the registration ID and my server registers to a specific topic for that registration ID. 
- Then when the user presses a button, I call my server API to send a message on that specific topic. 
- But my Android app that has already subscribed to the same specific topic, does not receive any notification. 
  And I'm not sure what is messed up.. :( I'll try subscribing to that same topic from another example. And see if that works.

**Comment by chirag200666** [comment]
you can look for solutions in stackoverflow
http://stackoverflow.com/questions/18570425/device-doesnt-receive-message-from-new-google-cloud-messaging-new-gcm
Or ask a new question there.

Just to see how it works you can use the google's sample app which subscribes the user to a topic named `global`  
https://developers.google.com/cloud-messaging/android/start 
then you can use node-gcm-iid to send messages to the global topic.

Hope it helps.

**Comment by vibgy** [comment]
Finally, figured it out.. Thanks for the pointer to the starter app. Now onto converting a registration token to a topic subscription and being able to get the GCM message sent on that topic, show up in the webapp.
